### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by oferavni** [ignacio-rocco/cnngeometric_matconvnet#2]
Hi,
I'm running the demo as is, and seem to get unexpected results such as:
![cars](https://user-images.githubusercontent.com/32934015/31777165-0d66d6bc-b4f6-11e7-9dff-e618b4406cda.jpg)
Would appreciate any ideas.
Thanks,
      Ofer

**Comment by ignacio-rocco** [comment]
Hi, 

This method is only obtaining about 57% PCK in PF. This means that about 40% of points will be wrong, so expect some bad cases.

However, you should also get some other results which look good.

Best,
Ignacio

**Comment by oferavni** [comment]
Hi Ignacio,

Still, there's some inconsistency I'd like to resolve. Figure 8 in the article shows:
![figure8](https://user-images.githubusercontent.com/32934015/31779889-e7901b90-b4fc-11e7-8c99-0a7903feef75.jpg)
 but when I run the demo on (what I assume are the same images), I get:
![carsfig8](https://user-images.githubusercontent.com/32934015/31780118-7501537c-b4fd-11e7-8b24-6e47e596dcd7.jpg)
Could these images be slightly different (e.g. resolution)? Do you expect slight differences to render such difference in the results?

Thanks so much for your prompt reply!
      Ofer

**Comment by ignacio-rocco** [comment]
Hi, 

You are right. I believe the images from the paper where generated with another version of the model, with slightly less overall performance.

However, for the particular example you are pointing out, the previous model was working better.

**Comment by oferavni** [comment]
Hi,

Do you have some non-trivial examples where the current model works well? Hope this may allow for some insights of what it does.

Thanks!
    Ofer

**Comment by ignacio-rocco** [comment]
Hi,

I'm sorry to hear that you are not satisfied with the results of the algorithm. This is ongoing research, I hope the next paper will be more satisfactory for you :)

Please make sure to check out some newer work by other colleagues such as SCNet www.di.ens.fr/willow/research/scnet/

Best,
Ignacio
