### ISSUE TITLE
How to visualizition CNN keypoints 

### ISSUE THREAD

**Issue by ketsuzhou** [ignacio-rocco/cnngeometric_matconvnet#3]
Hi, The CNN feature is area based ,and I don't understand how to visualization CNN key-point like fig.8 in your paper. could you help me .

**Comment by ignacio-rocco** [comment]
Hi, 

I think there is a confusion.

The keypoints in Fig.8 do not come from the CNN features. These are manually annotated keypoints provided with the Proposal FLow dataset which are used only for evaluation.

Does this make it more clear?

Fig.8 shows these points to help in qualitatively assesing the alignment. The code for generating this visualization is not included in the github code. Do you need it for anything in particular?

**Comment by ketsuzhou** [comment]
Thank you for your respond. To my think  is  the extracted CNN feature whether can locate in an area and combine with it's feature to retrieve semantic geometry structure of image, Like sift but more elegant

**Comment by ignacio-rocco** [comment]
Hi, features are extracted densly throughout the whole image, producing a 15x15 descriptor. There is no detection step as in SIFT.

Does this answer the question?

**Comment by ketsuzhou** [comment]
I'm not familiar with CNN，but to my intuition in shallow layer similar to sift,  convolution is used in feature extraction. it maybe wrong and thank you respond instantly

**Comment by ignacio-rocco** [comment]
SIFT feature extraction has two different [steps](http://www.vlfeat.org/overview/sift.html): (i) detection, and (ii) description. 

In CNNs these two steps are not always done. In our approach, we do not do any feature detection, but rather extract features densly on a 15x15 grid. 

You can see more in [these slides](https://www.youtube.com/watch?v=tgeD_Vqzx38).
